export type PartCategory = "cpu"|"gpu"|"motherboard"|"ram"|"storage"|"cooler"|"psu"|"case";
export type Currency = "CAD"|"CNY"|"USD";
export type PartMarketRegion = "US"|"CA"|"CN"|"GLOBAL";
export type GpuPowerConnector = "6-pin"|"8-pin"|"12VHPWR"|"12V-2x6";
export interface BasePart { id:string; category:PartCategory; name:string; brand:string; price:number; currency:Currency; imageUrl?:string; productUrl?:string; specSourceUrl?:string; priceSourceUrl?:string; priceKind?:"msrp"|"retail"|"reference"; priceAsOf?:string; marketRegions?:PartMarketRegion[]; performanceDataKind?:"curated"|"measured"|"derived"; tags:string[]; summary:string }
export interface CpuPart extends BasePart { category:"cpu"; socket:string; family?:string; memoryTypes?:("DDR4"|"DDR5")[]; cores:number; threads:number; baseClockGHz?:number; boostClockGHz?:number; tdpWatts:number; l3CacheMb?:number; has3dVCache?:boolean; maxMemorySpeedMt?:number; gamingScore:number; productivityScore:number; tier:"entry"|"mid"|"high"|"enthusiast" }
export interface GpuPart extends BasePart { category:"gpu"; chipset:string; vramGb:number; tdpWatts:number; lengthMm:number; thicknessSlots?:number; powerConnector?:GpuPowerConnector; powerConnectorCount?:number; computeEcosystems?:("cuda"|"rocm"|"hip"|"oneapi")[]; videoEncoders?:("h264"|"hevc"|"av1")[]; gamingScore1080p:number; gamingScore1440p:number; gamingScore4k:number; aiScore:number; cuda:boolean }
export interface MotherboardPart extends BasePart { category:"motherboard"; socket:string; chipset:string; formFactor:"ATX"|"Micro-ATX"|"Mini-ITX"; memoryType:"DDR4"|"DDR5"; maxMemoryGb:number; ramSlots?:number; m2Slots:number; storageInterfaces:("NVMe"|"SATA")[]; cpuTiers:("entry"|"mid"|"high"|"enthusiast")[]; supportedCpuFamilies?:string[]; minimumBiosByCpuFamily?:Record<string,string> }
export interface RamPart extends BasePart { category:"ram"; memoryType:"DDR4"|"DDR5"; capacityGb:number; speedMt:number; sticks:number; casLatency?:number; ratedVoltage?:number; profile?:"JEDEC"|"XMP"|"EXPO"|"XMP+EXPO"; ranks?:number; dramMaker?:string; qvlMotherboardIds?:string[] }
export interface StoragePart extends BasePart { category:"storage"; capacityTb:number; interface:"NVMe"|"SATA"; readSpeedMb?:number; writeSpeedMb?:number; sustainedWriteMb?:number; nandType?:"SLC"|"MLC"|"TLC"|"QLC"; hasDram?:boolean; tbw?:number; warrantyYears?:number }
export interface CoolerPart extends BasePart { category:"cooler"; supportedSockets:string[]; tdpRatingWatts:number; heightMm?:number; type:"air"|"aio"; radiatorSizeMm?:120|140|240|280|360|420; radiatorThicknessMm?:number }
export interface PsuPart extends BasePart { category:"psu"; wattage:number; efficiency:"Bronze"|"Gold"|"Platinum"|"Titanium"; formFactor:"ATX"|"SFX"; modular:boolean; atxVersion?:"2.x"|"3.0"|"3.1"; lengthMm?:number; pcie8PinConnectors?:number; twelveV2x6Connectors?:number }
export interface CasePart extends BasePart { category:"case"; supportedMotherboardFormFactors:("ATX"|"Micro-ATX"|"Mini-ITX")[]; maxGpuLengthMm:number; maxGpuThicknessSlots?:number; maxCoolerHeightMm:number; supportedRadiatorSizesMm?:(120|140|240|280|360|420)[]; psuFormFactors:("ATX"|"SFX")[]; maxPsuLengthMm?:number }
export type Part = CpuPart|GpuPart|MotherboardPart|RamPart|StoragePart|CoolerPart|PsuPart|CasePart;
export type BuildParts = { cpu:CpuPart; gpu:GpuPart; motherboard:MotherboardPart; ram:RamPart; storage:StoragePart; cooler:CoolerPart; psu:PsuPart; case:CasePart };
