import type { BuildParts } from "@/types/parts";
import type { CompatibilityResult, CompatibilityStatus } from "@/types/compatibility";
const result=(id:string,status:CompatibilityStatus,rule:string,message:string,relatedParts:string[]):CompatibilityResult=>({id,status,rule,message,relatedParts});
export function estimateWattage(p:BuildParts){return Math.round(p.cpu.tdpWatts+p.gpu.tdpWatts+85+(p.ram.capacityGb/8)*3+p.storage.capacityTb*5)}
export function checkCompatibility(p:BuildParts):CompatibilityResult[]{
 const watts=estimateWattage(p), required=Math.ceil(watts*1.35/50)*50, headroom=p.psu.wattage/watts;
 return [
  result("socket",p.cpu.socket===p.motherboard.socket?"PASS":"FAIL","CPU socket",p.cpu.socket===p.motherboard.socket?`${p.cpu.name} uses ${p.cpu.socket}, matching ${p.motherboard.name}.`:`${p.cpu.name} uses ${p.cpu.socket}, but ${p.motherboard.name} uses ${p.motherboard.socket}.`,[p.cpu.id,p.motherboard.id]),
  result("memory",p.ram.memoryType===p.motherboard.memoryType?"PASS":"FAIL","Memory type",p.ram.memoryType===p.motherboard.memoryType?`${p.ram.memoryType} memory matches the motherboard.`:`${p.ram.memoryType} RAM cannot be used with a ${p.motherboard.memoryType} motherboard.`,[p.ram.id,p.motherboard.id]),
  result("form",p.case.supportedMotherboardFormFactors.includes(p.motherboard.formFactor)?"PASS":"FAIL","Motherboard fit",p.case.supportedMotherboardFormFactors.includes(p.motherboard.formFactor)?`${p.motherboard.formFactor} motherboard fits inside ${p.case.name}.`:`${p.case.name} does not support ${p.motherboard.formFactor} motherboards.`,[p.case.id,p.motherboard.id]),
  result("gpu-length",p.gpu.lengthMm<=p.case.maxGpuLengthMm?"PASS":"FAIL","GPU clearance",p.gpu.lengthMm<=p.case.maxGpuLengthMm?`${p.gpu.name} is ${p.gpu.lengthMm}mm and fits the ${p.case.maxGpuLengthMm}mm clearance.`:`GPU length ${p.gpu.lengthMm}mm exceeds the case maximum of ${p.case.maxGpuLengthMm}mm.`,[p.gpu.id,p.case.id]),
  result("cooler-height",p.cooler.type==="aio"||!p.cooler.heightMm||p.cooler.heightMm<=p.case.maxCoolerHeightMm?"PASS":"FAIL","Cooler clearance",p.cooler.type==="aio"?`${p.cooler.name} uses a radiator mount instead of tower clearance.`:(p.cooler.heightMm||0)<=p.case.maxCoolerHeightMm?`${p.cooler.name} fits with ${p.case.maxCoolerHeightMm-(p.cooler.heightMm||0)}mm clearance.`:`Cooler height exceeds the case maximum.`,[p.cooler.id,p.case.id]),
  result("power",p.psu.wattage>=required?(headroom<1.5?"WARNING":"PASS"):"FAIL","Power headroom",p.psu.wattage>=required?(headroom<1.5?`Estimated draw is ${watts}W. ${p.psu.wattage}W is safe, but the upgrade margin is modest.`:`Estimated draw is ${watts}W. ${p.psu.wattage}W provides healthy headroom.`):`Estimated draw is ${watts}W. At least ${required}W is required by the 1.35x rule.`,[p.psu.id,p.cpu.id,p.gpu.id]),
  result("psu-form",p.case.psuFormFactors.includes(p.psu.formFactor)?"PASS":"FAIL","PSU fit",p.case.psuFormFactors.includes(p.psu.formFactor)?`${p.psu.formFactor} PSU is supported by ${p.case.name}.`:`${p.case.name} does not support ${p.psu.formFactor} power supplies.`,[p.psu.id,p.case.id]),
  result("cooling",p.cooler.tdpRatingWatts>=p.cpu.tdpWatts?"PASS":"FAIL","Cooling capacity",p.cooler.tdpRatingWatts>=p.cpu.tdpWatts?`${p.cooler.tdpRatingWatts}W cooler rating covers the CPU's ${p.cpu.tdpWatts}W rating.`:`Cooler rating is below the CPU's ${p.cpu.tdpWatts}W requirement.`,[p.cooler.id,p.cpu.id]),
  result("chipset",p.motherboard.cpuTiers.includes(p.cpu.tier)?"PASS":"WARNING","Chipset pairing",p.motherboard.cpuTiers.includes(p.cpu.tier)?`${p.motherboard.chipset} is a sensible match for this ${p.cpu.tier}-tier CPU.`:`${p.motherboard.chipset} may constrain a ${p.cpu.tier}-tier CPU. Consider a higher-tier board.`,[p.motherboard.id,p.cpu.id]),
  result("storage",p.motherboard.storageInterfaces.includes(p.storage.interface)?"PASS":"FAIL","Storage interface",p.motherboard.storageInterfaces.includes(p.storage.interface)?`${p.storage.interface} storage is supported by the motherboard.`:`Motherboard does not support ${p.storage.interface} storage.`,[p.storage.id,p.motherboard.id])
 ];
}
